project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: dark
    foreground: light
    title: "Cheng-Han Yang"
    left:
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
