project:
  type: website
  output-dir: docs

website:
  title: ""
  site-url: https://cyang728.github.io
  navbar:
    background: light
    foreground: dark
    title: "Cheng-Han Yang"
    left:
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false